# Generated by Django 5.2 on 2025-04-21 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Carpool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Data')),
                ('direction', models.CharField(choices=[('one_way', 'Somente Ida'), ('round_trip', 'Ida e Volta')], default='round_trip', max_length=10, verbose_name='Direção')),
                ('fuel_price', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Preço do Combustível (R$)')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Observações')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Carona',
                'verbose_name_plural': 'Caronas',
                'ordering': ['-date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CarpoolParticipant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('has_paid', models.BooleanField(default=False, verbose_name='Pagou')),
                ('payment_date', models.DateField(blank=True, null=True, verbose_name='Data de Pagamento')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Participante de Carona',
                'verbose_name_plural': 'Participantes de Carona',
                'ordering': ['carpool', 'user'],
            },
        ),
        migrations.CreateModel(
            name='FuelPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Preço (R$)')),
                ('effective_date', models.DateField(verbose_name='Data de Vigência')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Preço de Combustível',
                'verbose_name_plural': 'Preços de Combustível',
                'ordering': ['-effective_date'],
            },
        ),
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nome da Rota')),
                ('distance_km', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Distância (km)')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Descrição')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativa')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Rota',
                'verbose_name_plural': 'Rotas',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(max_length=100, verbose_name='Modelo')),
                ('plate', models.CharField(max_length=20, verbose_name='Placa')),
                ('fuel_efficiency', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Consumo (km/l)')),
                ('capacity', models.PositiveSmallIntegerField(default=4, verbose_name='Capacidade')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Veículo',
                'verbose_name_plural': 'Veículos',
                'ordering': ['owner', 'model'],
            },
        ),
    ]
