# Generated by Django 5.2 on 2025-04-21 22:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('caronas_app', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='carpool',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_carpools', to=settings.AUTH_USER_MODEL, verbose_name='Criado por'),
        ),
        migrations.AddField(
            model_name='carpool',
            name='driver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='driven_carpools', to=settings.AUTH_USER_MODEL, verbose_name='Motorista'),
        ),
        migrations.AddField(
            model_name='carpoolparticipant',
            name='carpool',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='caronas_app.carpool', verbose_name='Carona'),
        ),
        migrations.AddField(
            model_name='carpoolparticipant',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='carpool_participations', to=settings.AUTH_USER_MODEL, verbose_name='Participante'),
        ),
        migrations.AddField(
            model_name='fuelprice',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fuel_prices', to=settings.AUTH_USER_MODEL, verbose_name='Criado por'),
        ),
        migrations.AddField(
            model_name='carpool',
            name='route',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='carpools', to='caronas_app.route', verbose_name='Rota'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicles', to=settings.AUTH_USER_MODEL, verbose_name='Proprietário'),
        ),
        migrations.AddField(
            model_name='carpool',
            name='vehicle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='carpools', to='caronas_app.vehicle', verbose_name='Veículo'),
        ),
        migrations.AlterUniqueTogether(
            name='carpoolparticipant',
            unique_together={('carpool', 'user')},
        ),
    ]
